"""init schema: tenants, themes, companies, parse_runs, run_companies

Revision ID: bd00e9275c7c
Revises: 
Create Date: 2026-05-08 12:48:33.610967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd00e9275c7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('google_sheet_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('phone_normalized', sa.String(length=20), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('okved', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Text(), nullable=True),
    sa.Column('profit', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_company_tenant_inn', ['tenant_id', 'inn'], unique=False)
        batch_op.create_index('ix_company_tenant_ogrn', ['tenant_id', 'ogrn'], unique=False)
        batch_op.create_index('ix_company_tenant_phone', ['tenant_id', 'phone_normalized'], unique=False)

    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('filters_hash', sa.String(length=64), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'filters_hash', name='uq_theme_tenant_hash')
    )
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.create_index('ix_theme_tenant_last_used', ['tenant_id', 'last_used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_themes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('parse_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_new', sa.Integer(), nullable=False),
    sa.Column('total_found_in_source', sa.Integer(), nullable=True),
    sa.Column('total_new', sa.Integer(), nullable=False),
    sa.Column('total_skipped', sa.Integer(), nullable=False),
    sa.Column('sheet_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parse_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parse_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parse_runs_theme_id'), ['theme_id'], unique=False)

    op.create_table('run_companies',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['parse_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'company_id')
    )
    with op.batch_alter_table('run_companies', schema=None) as batch_op:
        batch_op.create_index('ix_runcompany_company', ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_companies', schema=None) as batch_op:
        batch_op.drop_index('ix_runcompany_company')

    op.drop_table('run_companies')
    with op.batch_alter_table('parse_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parse_runs_theme_id'))
        batch_op.drop_index(batch_op.f('ix_parse_runs_tenant_id'))

    op.drop_table('parse_runs')
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_themes_tenant_id'))
        batch_op.drop_index('ix_theme_tenant_last_used')

    op.drop_table('themes')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('ix_company_tenant_phone')
        batch_op.drop_index('ix_company_tenant_ogrn')
        batch_op.drop_index('ix_company_tenant_inn')
        batch_op.drop_index(batch_op.f('ix_companies_tenant_id'))

    op.drop_table('companies')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_telegram_user_id'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
